name: Check JSON and notify of time change

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read file contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "maintenance-time.json"
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.HOOK }}
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: "${ steps.read_file.outputs.contents }"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
